### ISSUE TITLE
0.7 mouse target profile 

### ISSUE THREAD

**Issue by Alexander4788** [iliran11/typing-game-2#23]
![Mouse on the profile](https://user-images.githubusercontent.com/46414084/54914940-cc6f0b80-4efe-11e9-901a-b6b6a224e817.jpeg)

-When the mouse is on the profile, the cursor does not change to click

**Comment by iliran11** [comment]
fixed in 7.0.1

**Comment by Alexander4788** [comment]
the bug still there in 0.9.2v 
btw same thing happens on the "Sign Up" button
